[project]
name = "moonlight"
version = "0.4.1"
description = "Wizard101 traffic decoder"
authors = [
    { name = "Ethan Zeigler", email = "ethanzeigler@gmail.com" },
    { name = "Kronos Authors" },
]
requires-python = ">=3.12,<4"
readme = "README.md"
license = "GPL-3.0-only"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "printrospector",
    "katsuba",
    "click>=8.0.4,<9",
    "colorama>=0.4.4,<0.5",
    "scapy>=2.5.0,<3",
]

[project.urls]
Repository = "https://github.com/kronos-project/moonlight"

[project.scripts]
moonlight = "moonlight.__main__:cli_cmd"

[dependency-groups]
dev = [
    "pytest>=9.0.3,<10",
    "black>=26.3.1,<27",
    "pre-commit>=2.17.0,<3",
    "ipython>=8.10.0,<9",
    "ipykernel>=6.9.2,<7",
    "snakeviz>=2.1.1,<3",
    "pyright>=1.1.326,<2",
]

[tool.uv]
default-groups = "all"

[tool.uv.sources]
printrospector = { git = "https://gitlab.com/vale_/printrospector", rev = "main" }
katsuba = { git = "https://github.com/vbe0201/katsuba.git", rev = "36e296f6c6ab21459edbd61d8ba333c950e9ac44", subdirectory = "src/katsuba-py" }

[tool.uv.build-backend]
module-root = ""
source-include = [
    "moonlight/**",
    "test/**",
    "poetry.lock",
    "pyproject.toml",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "line-too-long", # We'll let black handle this. There are cases when long lines are okay.
]

[tool.pyright]
include = ["mooonlight"]
